# Generated by Django 5.2.9 on 2025-12-22 12:25

import django.core.validators
import django.db.models.deletion
import tournament.validations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome do torneio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do torneio')),
                ('status', models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('P', 'Paused'), ('C', 'Canceled'), ('U', 'Unstarted')], default='U', max_length=1, verbose_name='Status do torneio')),
                ('max_enrrolment', models.IntegerField(validators=[tournament.validations.even_number_validate, django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(16)], verbose_name='Maximo de inscrições')),
                ('current_stage', models.IntegerField(verbose_name='Etapa atual')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Dono do torneio')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
            },
        ),
    ]
